### ISSUE TITLE
Unable to start ledcontrol

### ISSUE THREAD

**Issue by iamashwin99** [jackw01/led-control#56]
My installation from  the master branch seems to have gone through (nothing to show otherwise) , however when I run the program I get the following error:

```shell
$ sudo ledcontrol --port 80 --led_count 200
Using default linear pixel mapping (200 LEDs)
Can't open device file
: No such device or address
Traceback (most recent call last):
  File "/usr/local/bin/ledcontrol", line 33, in <module>
    sys.exit(load_entry_point('led-control', 'console_scripts', 'ledcontrol')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lights/src/led-control/ledcontrol/__init__.py", line 43, in main
    app = create_app(args.led_count,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lights/src/led-control/ledcontrol/app.py", line 47, in create_app
    leds = LEDController(led_count,
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lights/src/led-control/ledcontrol/ledcontroller.py", line 90, in __init__
    raise RuntimeError('ws2811_init failed with code {0} ({1})'.format(resp, str_resp))
RuntimeError: ws2811_init failed with code -9 (Failed to create mailbox device)
```

Does anyone one have any idea what might be going wrong

**Comment by jackw01** [comment]
What platform are you on?

**Comment by iamashwin99** [comment]
Raspberry Pi 4B with Debian 11

**Comment by jackw01** [comment]
Please search for your error message in the issues at https://github.com/jgarff/rpi_ws281x or report this over there - it looks like it may take some effort to get this library to work on non-Raspbian operating systems.
